Repository ietf-tapswg/api-drafts, pull requests merged in 2019-07, with the labels that each got.

#321 Merge Message References and Message Contexts and enable their use for Requests/Response protocols
  draft-ietf-taps-interface.md
Labels: API

#333 Make protocol-specific mappings in TAPS Implementation more rigorous
  draft-ietf-taps-impl.md
Labels: Implementation

#328 Add Transport Property Profiles
  draft-ietf-taps-interface.md
Labels: API, discuss
