Repository ietf-tapswg/api-drafts, pull requests merged in 2020-10, with the labels that each got.

#679 Clarifying example for partial receives. Closes #669.
  draft-ietf-taps-interface.md
Labels: API

#678 Remove "excessive retransmissions". Closes #677.
  draft-ietf-taps-interface.md
Labels: API

#674 move text on early name binding to privacy consideration
  draft-ietf-taps-interface.md
Labels: API

#643 Add new sections on keep alives
  draft-ietf-taps-interface.md
Labels: API

#683 Update draft-ietf-taps-interface.md
  draft-ietf-taps-interface.md
Labels: API, editorial

#614 Edits on Section on Handling Path Changes
  draft-ietf-taps-impl.md
Labels: Implementation

#680 Inherit some msg defaults from the connection, and divide fragmentation into layers 3 and 4.
  draft-ietf-taps-interface.md
Labels: API

#686 Connection properties: clarify that no guarantees are given for priority,…
  draft-ietf-taps-interface.md
Labels: API
