Repository ietf-tapswg/api-drafts, pull requests merged in 2020-05, with the labels that each got.

#574 Address editorial comments on Implementation
  draft-ietf-taps-impl.md
Labels: Implementation

#487 Make the singular transmission text clearer
  draft-ietf-taps-impl.md
Labels: Implementation

#565 Sentence about minIncompleteLength when rcv. on streams
  draft-ietf-taps-impl.md
Labels: Implementation

#582 Editorial update to message properties in draft-ietf-taps-impl.md
  draft-ietf-taps-impl.md
Labels: Implementation

#583 Rewording of Section 4.1.5 on Properties
  draft-ietf-taps-impl.md
Labels: Implementation, review

#581 Remove specification that message is bytes-like
  draft-ietf-taps-interface.md
Labels: API
