Repository ietf-tapswg/api-drafts, pull requests merged in 2020-03, with the labels that each got.

#463 Mostly Editorial changes on Capacity Profile
  draft-ietf-taps-interface.md
Labels: API

#497 Refactor Local Address Preference, fixes #436
  draft-ietf-taps-interface.md
Labels: API

#511 Move algorithm text to Implementation draft, make Interface draft more flexible
  draft-ietf-taps-impl.md
  draft-ietf-taps-interface.md
Labels: API, Implementation

#502 Clean up unnecessary normative language in arch
  draft-ietf-taps-arch.md
Labels: Architecture
