Repository ietf-tapswg/api-drafts, pull requests merged in 2020-04, with the labels that each got.

#483 Minor API nits
  draft-ietf-taps-interface.md
Labels: API

#558 Clarifications about per-connection vs per-message defaults
  draft-ietf-taps-interface.md
Labels: API

#562 Connection state diagram
  draft-ietf-taps-interface.md
Labels: API

#560 Architecture NiT: /assumes/
  draft-ietf-taps-arch.md
Labels: Architecture

#561 Replace "idempotent" with "safely replayable" everywhere
  draft-ietf-taps-impl.md
  draft-ietf-taps-interface.md
Labels: API, Implementation

#557 Define a new type to use when selection properties are queried
  draft-ietf-taps-interface.md
Labels: API

#572 Fix three oddities in the abstract of draft-ietf-taps-interface
  draft-ietf-taps-interface.md
Labels: API, editorial

#573 NiTs in section 1
  draft-ietf-taps-interface.md
Labels: API, editorial

#564 Consolidate normative language in architecture
  draft-ietf-taps-arch.md
  metadata.min.js
Labels: Architecture
