Repository ietf-tapswg/api-drafts, pull requests merged in 2021-07, with the labels that each got.

#863 Re-group managing properties & protocol instances
  draft-ietf-taps-interface.md
Labels: API, editorial

#862 Help UDP fit wrt connection
  draft-ietf-taps-arch.md
Labels: Architecture

#857 Fixes #812
  draft-ietf-taps-interface.md
Labels: API

#866 Preconnections are just structs
  draft-ietf-taps-interface.md
Labels: API

#856 Editorial nits
  draft-ietf-taps-interface.md
Labels: API, editorial
