Repository ietf-tapswg/api-drafts, pull requests merged in 2021-12, with the labels that each got.

#963 Arch tidy of mix concerns
  draft-ietf-taps-arch.md
Labels: Architecture

#964 Special values and update definition of "numeric"; replaces #930.
  draft-ietf-taps-interface.md
Labels: API, editorial

#965 Clarify Pooled Connections vs. Connection Groups. Resolves #956.
  draft-ietf-taps-impl.md
Labels: Implementation, editorial

#966 Be explicit about objects being treated as call-by-value
  draft-ietf-taps-interface.md
Labels: API
