Repository ietf-tapswg/api-drafts, pull requests merged in 2021-06, with the labels that each got.

#830 Add appendix note about object freeing
  draft-ietf-taps-interface.md
Labels: API

#827 Explicitly distinguish Callbacks from Events
  draft-ietf-taps-interface.md
Labels: API

#826 Clarify applicability of specific properties; fix #789
  draft-ietf-taps-interface.md
Labels: API

#847 Clarifications around Connections
  draft-ietf-taps-interface.md
Labels: API, editorial

#836 Trying to add some policy to the path selection
  draft-ietf-taps-interface.md
Labels: API

#795 Hopefully clearer text for the ReceiveError Event.
  draft-ietf-taps-interface.md
Labels: API

#845 Update names full checksum conn. properties
  draft-ietf-taps-interface.md
Labels: API

#771 Clarify Events upon various close / abort calls.
  draft-ietf-taps-interface.md
Labels: API

#858 PR to align Capacity profile with API
  draft-ietf-taps-impl.md
Labels: Implementation
