Repository ietf-tapswg/api-drafts, pull requests merged in 2021-10, with the labels that each got.

#924 A few simple editorial fixes from the ART-ART review.
  draft-ietf-taps-interface.md
Labels: API, editorial

#925 Remove a paragraph because it doesn't fit and doesn't add value.
  draft-ietf-taps-interface.md
Labels: API, editorial

#926 Change first appearance of "cloning" and add forward reference.
  draft-ietf-taps-interface.md
Labels: API, editorial

#927 Be more specific than "alphanumeric"
  draft-ietf-taps-interface.md
Labels: API, editorial

#938 Make architecture nicer (Many edits)
  draft-ietf-taps-arch.md
Labels: Architecture

#932 ARCH Example completion of a read call
  draft-ietf-taps-arch.md
Labels: Architecture

#942 Caching and racing in implementation intro
  draft-ietf-taps-arch.md
Labels: Architecture

#949 Remove a MUST NOT
  draft-ietf-taps-interface.md
Labels: API, editorial

#952 Minset: Fixing wrong statement about missing soft error, name cleanup
  draft-ietf-taps-interface.md
Labels: API
