Repository ietf-tapswg/api-drafts, pull requests merged in 2021-05, with the labels that each got.

#769 SCTP stream mapping, closes #708. (manual re-application of PR #722)
  draft-ietf-taps-impl.md
Labels: Implementation

#786 Proposed editorial changes to abstract and intro
  draft-ietf-taps-interface.md
Labels: API

#787 PR for when a transport system replays messages
  draft-ietf-taps-impl.md
Labels: API

#793 Tiny minset fix
  draft-ietf-taps-interface.md
Labels: API

#794 Fixes around Clone and entanglement
  draft-ietf-taps-interface.md
Labels: API

#796 Remove one confusing sentence (#790)
  draft-ietf-taps-interface.md
Labels: API

#797 Remove the mention of "hierarchy" in priority text
  draft-ietf-taps-interface.md
Labels: API

#768 Restructure tree structure
  draft-ietf-taps-impl.md
Labels: Implementation

#828 Ignore preservation of message boundaries for selection by default.
  draft-ietf-taps-interface.md
Labels: API

#834 Suggestion for no fragmentation
  draft-ietf-taps-interface.md
Labels: API

#833 Transport Segmentation
  draft-ietf-taps-interface.md
Labels: API

#840 Fix Case of Loc/Remote
  draft-ietf-taps-arch.md
Labels: Architecture, editorial

#839 Unconfuse checksum for gorry
  draft-ietf-taps-interface.md
Labels: API

#837 Not unreliable, but no reliability guarentees.
  draft-ietf-taps-interface.md
Labels: API, editorial

#841 Local/Remote in Impl
  draft-ietf-taps-impl.md
Labels: API, Architecture, Implementation

#838 Local/Remote Endpoints
  draft-ietf-taps-interface.md
Labels: API, editorial
