Repository ietf-tapswg/api-drafts, pull requests merged in 2021-09, with the labels that each got.

#893 attempt to improve preconnection draft-ietf-taps-arch.md
  draft-ietf-taps-arch.md
Labels: Implementation

#922 Author cleanup
  draft-ietf-taps-impl.md
Labels: Implementation

#921 Add a ReceivedPartial example
  draft-ietf-taps-interface.md
Labels: API

#923 Describe racing in Arch intro
  draft-ietf-taps-arch.md
Labels: Architecture
