Repository ietf-tapswg/api-drafts, pull requests merged in 2021-02, with the labels that each got.

#687 Improve API abstraction #658
  draft-ietf-taps-interface.md
Labels: API, ready for text

#728 Add a security consideration about partial messages
  draft-ietf-taps-interface.md
Labels: API

#733 Update affiliation of P. Tiesel
  draft-ietf-taps-arch.md
  draft-ietf-taps-impl.md
  draft-ietf-taps-interface.md
Labels: editorial

#725 Fix "confirmed route". Resolves #703
  draft-ietf-taps-impl.md
Labels: Implementation, editorial

#734 Separate connection context and groups - closes #721
  draft-ietf-taps-arch.md
  draft-ietf-taps-interface.md
Labels: API, Architecture
