Repository ietf-tapswg/api-drafts, pull requests merged in 2021-04, with the labels that each got.

#740 Small updates to the minset appendix for consistency
  draft-ietf-taps-interface.md
Labels: API, editorial

#742 Bring the multipath text in line with the API
  draft-ietf-taps-impl.md
  draft-ietf-taps-interface.md
Labels: Implementation

#745 Editorial rollup
  draft-ietf-taps-impl.md
Labels: Implementation, editorial

#748 Clarify "consumed" and "failed to send" timing.
  draft-ietf-taps-impl.md
Labels: Implementation, editorial

#767 Editorial rollup, bis.
  draft-ietf-taps-impl.md
Labels: Implementation, editorial

#770 Events upon Clone
  draft-ietf-taps-interface.md
Labels: API

#783 Update draft-ietf-taps-interface.md
  draft-ietf-taps-interface.md
Labels: API
