Repository ietf-tapswg/api-drafts, pull requests merged in 2022-06, with the labels that each got.

#1039 Segmentation: Fixing a few nits, but also changing a "can" into "will"
  draft-ietf-taps-interface.md
Labels: API

#1022 Soften order of operations text
  draft-ietf-taps-impl.md
Labels: Implementation

#1045 Incorporate Kyle's suggestions
  draft-ietf-taps-impl.md
Labels: Implementation

#1042 Address SECDIR review of -arch
  draft-ietf-taps-arch.md
Labels: Architecture
