Repository ietf-tapswg/api-drafts, pull requests merged in 2022-09, with the labels that each got.

#1051 Remove appendix B
  draft-ietf-taps-impl.md
Labels: Implementation

#1059 Fixing property names and their references
  draft-ietf-taps-impl.md
  draft-ietf-taps-interface.md
Labels: API, Implementation

#1062 Remove mention of ICMP errors for multicast receive
  draft-ietf-taps-impl.md
Labels: Implementation

#1061 Add notation reference for framers
  draft-ietf-taps-impl.md
Labels: Implementation

#1058 Clone causes a ConnectionReceived event.
  draft-ietf-taps-interface.md
Labels: API

#1063 Align framer parameter names with API
  draft-ietf-taps-impl.md
Labels: Implementation

#1067 Editorial updates for implementation
  draft-ietf-taps-impl.md
Labels: Implementation

#1066 Introduce racing more clearly
  draft-ietf-taps-impl.md
Labels: Implementation

#1060 Describe metadata-only messages
  draft-ietf-taps-impl.md
Labels: Implementation

#1050 Sketch alternative multicast model – #1021 reloaded
  draft-ietf-taps-interface.md
Labels: API, discuss
