Repository ietf-tapswg/api-drafts, pull requests merged in 2023-11, with the labels that each got.

#1446 Point at Software Heritage Archive
  draft-ietf-taps-impl.md
Labels: Implementation

#1445 Section 11: not all state transitions have events
  draft-ietf-taps-interface.md
Labels: API

#1447 Clarify multiple Local/remote endpoints
  draft-ietf-taps-interface.md
Labels: API, From a partial review

#1437 Three new read-only Connection properties
  draft-ietf-taps-interface.md
Labels: API

#1434 Where do interface names come from?
  draft-ietf-taps-interface.md
Labels: API

#1448 Make IPv4 and IPv6 port numbers consistent
  draft-ietf-taps-impl.md
Labels: Implementation, From a partial review

#1443 What about zero Integer or Numeric values?
  draft-ietf-taps-interface.md
Labels: API

#1442 How to choose security protocols is out of scope, but cite RFC 8922
  draft-ietf-taps-interface.md
Labels: API

#1441 Well-known service names come from the IANA list
  draft-ietf-taps-interface.md
Labels: API

#1440 Not "values" for "Connectedness"
  draft-ietf-taps-impl.md
Labels: Implementation, editorial

#1450 Interfaces -> network paths
  draft-ietf-taps-interface.md
Labels: API

#1452 Explain stacked layers of keep alive protocols
  draft-ietf-taps-impl.md
Labels: Implementation

#1451 Rework aliases
  draft-ietf-taps-interface.md
Labels: API
