Repository ietf-tapswg/api-drafts, pull requests merged in 2023-09, with the labels that each got.

#1236 Nits, closes #1232.
  draft-ietf-taps-interface.md
Labels: API, editorial

#1251 More on Equivalence
  draft-ietf-taps-arch.md
Labels: Architecture

#1274 A tiny fix to one sentence
  draft-ietf-taps-arch.md
Labels: Architecture

#1269 Should remote endpoint include mcast group?
  draft-ietf-taps-arch.md
Labels: Architecture

#1271 Editorial fixes + Namespaces: distinguish vendors from IETF protocols + rephrasing "RFC series"
  draft-ietf-taps-interface.md
Labels: API, editorial

#1276 Endpoints v Endpoint Identifiers
  draft-ietf-taps-arch.md
Labels: Architecture

#1315 Fix UDP(-Lite)
  draft-ietf-taps-impl.md
Labels: Implementation, editorial

#1316 Replace without corruption
  draft-ietf-taps-interface.md
Labels: API

#1317 Generic Properties
  draft-ietf-taps-interface.md
Labels: API

#1356 Remove the use of "native"
  draft-ietf-taps-arch.md
  draft-ietf-taps-impl.md
  draft-ietf-taps-interface.md
Labels: editorial

#1382 Rework datagram in example
  draft-ietf-taps-interface.md
Labels: API

#1383 Fix MPS text
  draft-ietf-taps-interface.md
Labels: API

#1380 Fix word rendezvousing and purposes in API
  draft-ietf-taps-interface.md
Labels: API, editorial
