Repository ietf-tapswg/api-drafts, pull requests merged in 2023-02, with the labels that each got.

#1108 Add ranking criteria for protocol options
  draft-ietf-taps-impl.md
Labels: Implementation

#1109 Normatively forbid multiple identifiers per endpoint.
  draft-ietf-taps-interface.md
Labels: API

#1118 /transport object/Connection/
  draft-ietf-taps-arch.md
Labels: Architecture
