Repository ietf-tapswg/api-drafts, pull requests merged in 2023-10, with the labels that each got.

#1394 Make it clearer that Messages can be spread across multiple packets
  draft-ietf-taps-arch.md
Labels: Architecture

#1392 Nits
  draft-ietf-taps-arch.md
  draft-ietf-taps-impl.md
  draft-ietf-taps-interface.md
Labels: API, Architecture, Implementation

#1391 Non-Preference Selection Properties don't change their type
  draft-ietf-taps-interface.md
Labels: API

#1388 s/Collection/Set
  draft-ietf-taps-interface.md
Labels: API

#1318 Create IANA registry for Tansport Property Namespace
  draft-ietf-taps-interface.md
Labels: API, discuss

#1393 Mention the Connection priority in the scheduler property description
  draft-ietf-taps-interface.md
Labels: API

#1396 Could/Can/Might rather than may
  draft-ietf-taps-interface.md
Labels: API

#1397 Explain errors for message properties
  draft-ietf-taps-interface.md
Labels: API

#1386 Endpoints and Endpoint Identifiers. Closes #1278.
  draft-ietf-taps-arch.md
  draft-ietf-taps-impl.md
  draft-ietf-taps-interface.md
Labels: API, Architecture, Implementation

#1398 Hostnames SHOULD be FQDNs
  draft-ietf-taps-interface.md
Labels: API

#1401 Make UTO more clearly a TCP example
  draft-ietf-taps-interface.md
Labels: API

#1414 Clarify "later control" of checksum coverage
  draft-ietf-taps-interface.md
Labels: API

#1405 HostName not Hostname
  draft-ietf-taps-interface.md
Labels: API, editorial

#1411 Apostrophes for boolean types and simplifying set-of-tuples text
  draft-ietf-taps-interface.md
Labels: API, editorial

#1415 s/other side/Remote Endpoint
  draft-ietf-taps-interface.md
Labels: API, editorial

#1419 Prioritization: don't talk about "performance"
  draft-ietf-taps-interface.md
Labels: API

#1418 Elaborate on preconnection reuse
  draft-ietf-taps-interface.md
Labels: API

#1417 Capitalize Integer (where it fits to do so)
  draft-ietf-taps-interface.md
Labels: API

#1400 Change hi<->lo priority
  draft-ietf-taps-interface.md
Labels: API

#1407 Rephrase batch sending
  draft-ietf-taps-impl.md
Labels: Implementation

#1387 Wording of receiver backpressure.
  draft-ietf-taps-interface.md
Labels: API

#1406 Clarify rate bounds
  draft-ietf-taps-interface.md
Labels: API

#1421 app SHOULD NOT assume that ignoring events is always safe
  draft-ietf-taps-interface.md
Labels: API

#1426 Reference RFC 5952
  draft-ietf-taps-interface.md
Labels: API

#1408 Protocol identifiers are strings, listed in the API doc., and shouldn't normally be used
  draft-ietf-taps-interface.md
Labels: API

#1410 Dealing with "if then" type clauses, try 2 (alternative to #1409)
  draft-ietf-taps-interface.md
Labels: API

#1427 Clarify PvD identification
  draft-ietf-taps-interface.md
Labels: API

#1422 Ignore => None
  draft-ietf-taps-interface.md
Labels: API

#1431 Add ephemeral port example
  draft-ietf-taps-interface.md
Labels: API

#1404 Make Transport Property Names more strict (and case-insenstitive)
  draft-ietf-taps-interface.md
Labels: API, discuss
