Repository ietf-tapswg/api-drafts, pull requests merged in 2023-06, with the labels that each got.

#1175 Resolves #1140 Handling connectionless protocols
  draft-ietf-taps-impl.md
Labels: Implementation

#1178 Fix DNS nits
  draft-ietf-taps-impl.md
Labels: Implementation

#1198 Clarify multiple remote endpoints
  draft-ietf-taps-interface.md
Labels: API

#1209 Tiny wording change on schedulers
  draft-ietf-taps-interface.md
Labels: API

#1208 Minor wording change in example in section 3.1.2.
  draft-ietf-taps-interface.md
Labels: API

#1206 Various editorial fixes from Genart review.
  draft-ietf-taps-interface.md
Labels: API, editorial
